### PR TITLE
Fixes Siri impatience and Colored Lights

### PR DESCRIPTION
**Pull request by pdlove**
Modified to allow sProperty and sTarget to be an array for setting several things at the same time on a device.

Moved call back to allow the plugin to verify the command is possible and the light is connected and then report back to Siri. (#14, #21, #23, #26)
Fixed color change lights in the case of Phillips Hue. It is likely that this fixed other color light too, but I was only able to test with that one brand. (#18)

### CODE REVIEW

**Comment by pdlove** [comment]
I added a few other options. Most notably the Window Shades.
I also added the ability to set the Garage Door to "Low Security" so Siri can Open and Close the garage door while the phone is locked if you acknowledge that's what you want and set the flag to true in the config file.

**Comment by techyowl** [comment]
@KraigM & @pdlove  ready to install this release as soon as it gets pushed to npm

**Comment by KraigM** [comment]
I've said it before and I will say it again, I strongly disagree with the "low security" option. Has any other homebridge plugin done that?

**Comment by pdlove** [comment]
@KraigM I don't mind removing that. The biggest thing on it is that it is very manual to enable and has some warnings in the code and probably shouldn't be on the help file. If we do yank it from here, let's also close the issue request on that so I'll quit thinking "I need to get that in there to remove the issue" :)

**Comment by msroest** [comment]
I'm with @KraigM on this the seems like allowing that is a pretty big hole and will open people up to liability

**Comment by KraigM** [comment]
Yeah go ahead and remove that and I will close the other issue

**Comment by techyowl** [comment]
oh I didn't even notice the low security option. I was mainly wanting the color light support.

**Comment by pdlove** [comment]
Low Security has been removed and will not be approached again on this or any plugin I approach. If anyone really wants to have it work like that, feel free to run the code I did prior to the most recent commit, but don't blame me if you lose valuables!

**Comment by KraigM** [comment]
@pdlove I made a slight modification to your fix of the "not responding problem" ^.  Which is funny because I'm pretty sure we are back to almost exactly the same code we found that we thought was weird and "fixed".  Im actually thinking either I or someone else put that in there as a hack to be fixed later. Anywho, I changed it to at least wait until the request had officially been made to wink and capture any errors that may have happened.  Does that look good to you?

**Comment by pdlove** [comment]
That's great. So if it can't communicate with Wink then Siri will still error out. I'm good with it.

**Pull request merged**
